spring.application.name=backup-service

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/backup_db
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

#JWT configuration
# You can set the JWT secret and expiration time using environment variables or default values
# Remember to set secret in .env file
#
# THIS IS NOT SECURE! DO NOT USE IN PRODUCTION!
#
jwt.secret=${JWT_SECRET:c87a1c0209d8f11c8dcecd289a2d82327d96750ba12a1eb30d82b0e69b1a6596}
jwt.expiration=3600000

# Logging configuration
logging.level.root=INFO
logging.level.pl.matkmiec.backup=DEBUG
logging.level.org.springframework=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10

# Rate limiter configuration - Resilience4j
# Login
resilience4j.ratelimiter.instances.login.registerHealthIndicator=true
resilience4j.ratelimiter.instances.login.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.login.limitForPeriod=5
resilience4j.ratelimiter.instances.login.timeoutDuration=5s
# Register
resilience4j.ratelimiter.instances.register.registerHealthIndicator=true
resilience4j.ratelimiter.instances.register.limitRefreshPeriod=10m
resilience4j.ratelimiter.instances.register.limitForPeriod=3 
resilience4j.ratelimiter.instances.register.timeoutDuration=5s
# Backup Upload
resilience4j.ratelimiter.instances.backupUpload.registerHealthIndicator=true
resilience4j.ratelimiter.instances.backupUpload.limitRefreshPeriod=1h
resilience4j.ratelimiter.instances.backupUpload.limitForPeriod=120
resilience4j.ratelimiter.instances.backupUpload.timeoutDuration=5s
# Backup Delete
resilience4j.ratelimiter.instances.backupDelete.registerHealthIndicator=true
resilience4j.ratelimiter.instances.backupDelete.limitRefreshPeriod=1h
resilience4j.ratelimiter.instances.backupDelete.limitForPeriod=30
resilience4j.ratelimiter.instances.backupDelete.timeoutDuration=5s
# Backup List
resilience4j.ratelimiter.instances.backupList.registerHealthIndicator=true
resilience4j.ratelimiter.instances.backupList.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.backupList.limitForPeriod=60
resilience4j.ratelimiter.instances.backupList.timeoutDuration=5s
# Backup Get
resilience4j.ratelimiter.instances.backupGet.registerHealthIndicator=true
resilience4j.ratelimiter.instances.backupGet.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.backupGet.limitForPeriod=60
resilience4j.ratelimiter.instances.backupGet.timeoutDuration=5s


