spring.application.name=backup-service

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/backup_db
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

#JWT configuration
# You can set the JWT secret and expiration time using environment variables or default values
# Remember to set secret in .env file
#
# THIS IS NOT SECURE! DO NOT USE IN PRODUCTION!
#
jwt.secret=${JWT_SECRET:c87a1c0209d8f11c8dcecd289a2d82327d96750ba12a1eb30d82b0e69b1a6596}
jwt.expiration=86400000


# Rate limiter configuration
resilence4j.ratelimiter.insances.login.registerHealthIndicator=true
resilence4j.ratelimiter.insances.login.limitRefreshPeriod=1m
resilence4j.ratelimiter.insances.login.limitForPeriod=5
resilence4j.ratelimiter.insances.login.timeoutDuration=5s

